#!/usr/bin/env bash

C_DIM="\e[0;90m"
C_INFO="\e[0;1;92m"
C_WARN="\e[0;1;93m"
C_ERROR="\e[0;1;91m"
C_PATH="\e[0;1;3;94m"
C_RESET="\e[0m"

_info() {
  echo -e "${C_DIM}:: ${C_INFO}INFO${C_RESET}${C_DIM} - $1${C_RESET}"
}

_warn() {
  echo -e "${C_DIM}:: ${C_WARN}WARN${C_RESET}${C_DIM} - $1${C_RESET}"
}

_error() {
  echo -e "${C_DIM}:: ${C_ERROR}ERROR${C_RESET}${C_DIM} - $1${C_RESET}"
}

BUILD_FOLDER="./build/"

if [[ "$OSTYPE" == "darwin"* ]]; then
  CMAKE_FLAGS="-DCMAKE_PREFIX_PATH=$(brew --prefix)"
  LOG_TEMPLATE="/tmp/r-type_client_$(id -u)_"
else
  CMAKE_FLAGS=
  LOG_TEMPLATE="/dev/shm/r-type_client_$(id -u)_"
fi

[[ ! -d "$BUILD_FOLDER/CMakeCache.txt" ]] && _info "Configuring CMake project..." && cmake -S . -B build $CMAKE_FLAGS

cmake --build build || exit 1

set -o monitor

declare -A client_pids
SERVER_PID=0

_client_logs() {
  for pid in "${!client_pids[@]}"; do
    if ! kill -0 "$pid" 2>/dev/null; then
      local id=${client_pids[$pid]}
      local log_file="$LOG_TEMPLATE$id.log"

      _info "Client $id (PID: ${C_PATH}$pid${C_DIM}) stopped!"
      if [ -f "$log_file" ]; then
        echo -e "${C_PATH}tail -n 15 $log_file${C_RESET}"
        tail -n 15 "$log_file"
        echo -e "${C_DIM}--- EOF --${C_RESET}"
      else
        _warn "$log_file not found"
      fi

      unset "client_pids[$pid]"
    fi
  done
}

trap _client_logs SIGCHLD

_cleanup() {
  _info "Stopping clients & server..."
  trap - SIGCHLD SIGINT EXIT

  if [ "$SERVER_PID" -ne 0 ] && kill -0 "$SERVER_PID" 2>/dev/null; then
    kill "$SERVER_PID" 2>/dev/null
  fi

  for pid in "${!client_pids[@]}"; do
    if kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null
    fi

    local id=${client_pids[$pid]}
    rm -f "$LOG_TEMPLATE$id.log"
  done

  exit 0
}

trap _cleanup SIGINT EXIT

for i in {1..4}; do
  _info "Starting ${C_PATH}r-type_client $i${C_DIM}..."
  ./build/r-type_client >"$LOG_TEMPLATE$i.log" 2>&1 &
  client_pids[$!]=$i
done

_info "Starting ${C_PATH}r-type_server${C_DIM}..."
./build/r-type_server &
SERVER_PID=$!

while kill -0 "$SERVER_PID" 2>/dev/null; do
  wait "$SERVER_PID" 2>/dev/null
done
